feat: implement retry mechanism on teleport jobs (#494)
* feat: implement retry mechanism on teleport jobs

* fix: adjust error messages to match the usual timeout

* fix: change triage job to use ubuntu-latest

* fix: remove superflous / from input descriptons

* feat: add job that would log the amount of pending pods after both jobs involing camunda deployment

* fix: ensure that the pending pod check for failback only runs if the workflow has actually gotten that far

* fix: enhance error message handling to only retry if deployment failed due to pending pods

* fix: operational-procedure should attempt running before rerun-failed-jobs

* fix: correctly sum pending pod count

* fix: better condition for failback pending check

* fix: keep second pending check as always as well after all

* fix: add fake error for debugging

* fix: try to trigger the workflow for debugging

* fix: try to see what happens if the error occurrs in the calling workflow

* fix: put debug error back in reusable workflow

* fix: use latest rerun-failed-run

* fix: use latest main branch version

* fix: remove debug error

* fix: remove push event that was used to trigger debug runs

---------

Signed-off-by: Balázs <96087935+bkenez@users.noreply.github.com>

diff --git a/.github/workflows/nightly_teleport_operational_procedure_stable.yml b/.github/workflows/nightly_teleport_operational_procedure_stable.yml
--- a/.github/workflows/nightly_teleport_operational_procedure_stable.yml
+++ b/.github/workflows/nightly_teleport_operational_procedure_stable.yml
@@ -29,8 +29,19 @@ concurrency:
     cancel-in-progress: true
 
 jobs:
+    triage:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Display notify_back_error_message if present
+              if: ${{ inputs.notify_back_error_message != '' }}
+              run: |
+                  echo "A previous workflow failed but has attempted to retry: ${{ inputs.notify_back_error_message }}"
+                  exit 1
+
     dynamic-matrix:
         runs-on: ubuntu-latest
+        needs:
+            - triage
         outputs:
             matrix: ${{ steps.generate-matrix.outputs.matrix }}
         steps:
@@ -58,6 +69,7 @@ jobs:
                   echo "${versions}"
                   echo "matrix=${versions}" >> "$GITHUB_OUTPUT"
 
+
     operational-procedure:
         needs:
             - dynamic-matrix
@@ -82,11 +94,31 @@ jobs:
             zeebeClusterSize: 8
         secrets: inherit
 
-    notify-on-failure:
+    rerun-failed-jobs:
+        if: failure() && fromJSON(github.run_attempt) < 3 && inputs.notify_back_error_message == ''
         runs-on: ubuntu-latest
-        if: github.event_name == 'schedule' && failure()
         needs:
             - operational-procedure
+        steps:
+            - name: Retrigger job
+              uses: camunda/infra-global-github-actions/rerun-failed-run@66bb8b91caf4c23a1044a67a11c852195d357193 # main at the time of 2025-03-17
+              with:
+                  error-messages: |
+                      PendingPodsError: Found
+                  run-id: ${{ github.run_id }}
+                  repository: ${{ github.repository }}
+                  vault-addr: ${{ secrets.VAULT_ADDR }}
+                  vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+                  vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+                  notify-back-on-error: 'true'
+
+
+    notify-on-failure:
+        runs-on: ubuntu-latest
+        if: failure() && (fromJSON(github.run_attempt) >= 3 || inputs.notify_back_error_message != '') && github.event_name == 'schedule'
+        needs:
+            - operational-procedure
+            - rerun-failed-jobs
         steps:
             - name: Notify in Slack in case of failure
               id: slack-notification
