feat: implement retry mechanism on teleport jobs

diff --git a/.github/workflows/nightly_teleport_operational_procedure_stable.yml b/.github/workflows/nightly_teleport_operational_procedure_stable.yml
--- a/.github/workflows/nightly_teleport_operational_procedure_stable.yml
+++ b/.github/workflows/nightly_teleport_operational_procedure_stable.yml
@@ -9,6 +9,10 @@ on:
             helm-versions:
                 description: The Helm versions to use as comma separated list
                 type: string
+            notify_back_error_message:
+                description: \ Error message if retry was not successful. This parameter is used for internal call back actions.
+                required: false
+                default: ''
     pull_request:
         branches-ignore:
             - stable/**
@@ -25,8 +29,19 @@ concurrency:
     cancel-in-progress: true
 
 jobs:
+    triage:
+        runs-on: ubuntu-22.04
+        steps:
+            - name: Display notify_back_error_message if present
+              if: ${{ inputs.notify_back_error_message != '' }}
+              run: |
+                  echo "A previous workflow failed but has attempted to retry: ${{ inputs.notify_back_error_message }}"
+                  exit 1
+
     dynamic-matrix:
         runs-on: ubuntu-latest
+        needs:
+            - triage
         outputs:
             matrix: ${{ steps.generate-matrix.outputs.matrix }}
         steps:
@@ -78,11 +93,30 @@ jobs:
             zeebeClusterSize: 8
         secrets: inherit
 
+    rerun-failed-jobs:
+        if: failure() && fromJSON(github.run_attempt) < 3 && inputs.notify_back_error_message == ''
+        runs-on: ubuntu-latest
+        steps:
+            - name: Retrigger job
+              uses: camunda/infra-global-github-actions/rerun-failed-run@a6261098b91e48a8db1802a58af5191eb498630c # main
+              with:
+                  error-messages: |
+                      lost communication with the server
+                      The runner has received a shutdown signal
+                  run-id: ${{ github.run_id }}
+                  repository: ${{ github.repository }}
+                  vault-addr: ${{ secrets.VAULT_ADDR }}
+                  vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+                  vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+                  notify-back-on-error: 'true'
+
+
     notify-on-failure:
         runs-on: ubuntu-latest
-        if: github.event_name == 'schedule' && failure()
+        if: failure() && (fromJSON(github.run_attempt) >= 3 || inputs.notify_back_error_message != '') && github.event_name == 'schedule'
         needs:
             - operational-procedure
+            - rerun-failed-jobs
         steps:
             - name: Notify in Slack in case of failure
               id: slack-notification
