fix: try to see what happens if the error occurrs in the calling workflow

diff --git a/.github/workflows/nightly_teleport_operational_procedure_stable.yml b/.github/workflows/nightly_teleport_operational_procedure_stable.yml
--- a/.github/workflows/nightly_teleport_operational_procedure_stable.yml
+++ b/.github/workflows/nightly_teleport_operational_procedure_stable.yml
@@ -75,6 +75,10 @@ jobs:
                   echo "${versions}"
                   echo "matrix=${versions}" >> "$GITHUB_OUTPUT"
 
+                  echo "::error ::PendingPodsError: Found"
+                  exit 1
+
+
     operational-procedure:
         needs:
             - dynamic-matrix
