fix: add fake error for debugging

diff --git a/.github/workflows/reusable_teleport_operational_procedure.yml b/.github/workflows/reusable_teleport_operational_procedure.yml
--- a/.github/workflows/reusable_teleport_operational_procedure.yml
+++ b/.github/workflows/reusable_teleport_operational_procedure.yml
@@ -238,6 +238,9 @@ jobs:
               id: deploy-camunda
               working-directory: ./test
               run: |
+                  # debug error
+                  echo "::error ::PendingPodsError: Found
+                  exit 1
                   set -euxo pipefail
                   go test --count=1 -v -timeout 30m -run TestAWSDeployDualRegCamunda
 
